[package]
name = "linker-utils"
version.workspace = true
edition = "2021"
repository.workspace = true

[dependencies]
object = { version = "0.36.5", default-features = false, features = [
    "elf",
    "read_core",
    "std",
    "unaligned",
] }

[lints]
workspace = true
